name: dialog_polyfill
version: 0.4.3-dev.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Polyfill for HTML dialog element
homepage: https://github.com/rwl/dialog_polyfill
dependencies:
  browser: any
dev_dependencies:
  web_components: any
