name: dialog_polyfill
version: 0.4.3-1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Polyfill for HTML dialog element
homepage: https://github.com/rwl/dialog_polyfill
dev_dependencies:
  browser: any
